# Generated by Django 4.0.1 on 2024-03-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=16, unique=True)),
                ('cardType', models.CharField(max_length=7)),
                ('cardCurrency', models.CharField(max_length=3)),
                ('CVV', models.CharField(max_length=3)),
                ('cardExpirationDate', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
