# Generated by Django 4.0.1 on 2024-03-01 15:00

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(default=None, max_length=254, null=True)),
                ('new_email_code', models.CharField(default=None, max_length=255, null=True)),
                ('new_email_code_expires', models.DateTimeField(default=None, null=True)),
                ('old_email_code', models.CharField(default=None, max_length=255, null=True)),
                ('old_email_code_expires', models.DateTimeField(default=None, null=True)),
                ('can_change_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/')),
                ('birthday', models.DateField()),
                ('activationCode', models.CharField(max_length=4)),
                ('expirationActivationCode', models.DateTimeField()),
                ('email_details', djongo.models.fields.JSONField(default=dict)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='CardIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
        migrations.CreateModel(
            name='AccountIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
        ),
    ]
