# Generated by Django 4.0.1 on 2024-03-04 12:02

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.AddField(
            model_name='users',
            name='resetPassword',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
