# Generated by Django 4.0.1 on 2024-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50, null=True)),
                ('accountNumber', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=15)),
                ('accountType', models.CharField(max_length=7)),
                ('accountCurrency', models.CharField(default='AMD', max_length=3)),
                ('created_at_registration', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
